version: "3"
services:
  blog_web_server:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - net
    depends_on:
      - redis_database_server

  redis_database_server:
    image: redis:latest
    command: redis-server
    volumes:
      - ../redis-data:/var/lib/redis
    networks:
      - net

networks:
  net:
    driver: bridge