version: "3"
services:
  blog_web_server:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
    extra_hosts:
      - "localhost:127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3